services:
  example-pytorch:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: example-pytorch
    ports:
      - "8888:8888"           # http://localhost:8888
    volumes:
      - ../../:/example-pytorch
    shm_size: "8gb"           # 大きめの共有メモリ（DataLoaderなどで有効）
    environment:
      - TZ=Asia/Tokyo
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    tty: true
    stdin_open: true
    command: ["jupyter", "lab", "--ip=0.0.0.0", "--allow-root", "--LabApp.token=''"]
