services:
  project:
    build:
      context: ./pytorch
      dockerfile: Dockerfile-cu129
    image: example-pytorch:latest
    container_name: example-pytorch
    gpus: all
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
