FROM nvidia/cuda:12.9.1-base-ubuntu24.04

RUN apt-get update && apt-get install -y \
    python3-pip \
    python3-venv \
    python-is-python3 \
    sudo \
    wget \
    git \
    vim

# virtualenv環境作成
ENV VENV_PATH=/opt/venv
RUN python3 -m venv $VENV_PATH
ENV PATH="$VENV_PATH/bin:$PATH"

# pip更新
RUN pip install --upgrade pip

# PyTorchインストール
RUN pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu129
RUN pip install torcheval torchinfo lightning

# その他パッケージのインストール
COPY common_requirements.txt ./tmp/
RUN pip install -r ./tmp/common_requirements.txt

WORKDIR /project

CMD ["/bin/bash"]
